// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAE0X-0LUTa2LU8aWpVWfhz8i1KthLN-T0',
    appId: '1:93720788382:web:f6f942b564a08f825c6a8f',
    messagingSenderId: '93720788382',
    projectId: 'twist-app-87036',
    authDomain: 'twist-app-87036.firebaseapp.com',
    storageBucket: 'twist-app-87036.firebasestorage.app',
    measurementId: 'G-K13BQ75CBE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaf-x9_QY_LgxpyKX6srAjNFfPabaYrmE',
    appId: '1:93720788382:android:01511632616166b85c6a8f',
    messagingSenderId: '93720788382',
    projectId: 'twist-app-87036',
    storageBucket: 'twist-app-87036.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2eMvcrjzWhkQL5Vqcm3H-XTFld098cM0',
    appId: '1:93720788382:ios:0e40da8d8b12b0825c6a8f',
    messagingSenderId: '93720788382',
    projectId: 'twist-app-87036',
    storageBucket: 'twist-app-87036.firebasestorage.app',
    iosBundleId: 'com.example.twistDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2eMvcrjzWhkQL5Vqcm3H-XTFld098cM0',
    appId: '1:93720788382:ios:0e40da8d8b12b0825c6a8f',
    messagingSenderId: '93720788382',
    projectId: 'twist-app-87036',
    storageBucket: 'twist-app-87036.firebasestorage.app',
    iosBundleId: 'com.example.twistDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAE0X-0LUTa2LU8aWpVWfhz8i1KthLN-T0',
    appId: '1:93720788382:web:e2a22db91eea83145c6a8f',
    messagingSenderId: '93720788382',
    projectId: 'twist-app-87036',
    authDomain: 'twist-app-87036.firebaseapp.com',
    storageBucket: 'twist-app-87036.firebasestorage.app',
    measurementId: 'G-HKZQ3JP364',
  );
}
